.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. vendetta_qt test_vendetta_qt
clean: FORCE
	$(MAKE) -C .. vendetta_qt_clean test_vendetta_qt_clean
check: FORCE
	$(MAKE) -C .. test_vendetta_qt_check
vendetta-qt vendetta-qt.exe: FORCE
	 $(MAKE) -C .. vendetta_qt
